### ISSUE TITLE
Redirect unauthenticated users accessing `/apply` to `/login`

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#131]
Unauthenticated users should log in first before accessing the application. However, this logic is currently not in the codebase yet. This can be done by simply calling `getUserIdentity` and checking whether the user is logged in on in the `page.tsx` for the `/apply` route.

**Comment by IanWearsHat** [comment]
Would #108 resolve this?

**Comment by samderanova** [comment]
Yes, I should have been working in #108 instead of creating a new issue, as @taesungh suggested in #125. I'll reopen it.
