### ISSUE TITLE
Restrict site builds unless specified

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#133]
As we reach ever closer to the daily 100 build limit of Vercel, we must be wary of the number of commits we make on each pull request as each one triggers a new build. @taesungh implemented a restriction in #106 we can apply to the site as well.

**Comment by taesungh** [comment]
Manually disabled the [Deploy Preview workflow](https://github.com/HackAtUCI/irvinehacks-site-2024/actions/workflows/deploy-preview.yml) for now
