### ISSUE TITLE
Import admin console from last year's website

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#185]
In relation to #173, this issue involves setting up the frontend of the admin console to allow the applications team to review applications properly.

Specifically, for now, we can directly import the admin console from last year's website, meaning that it will mainly be a client side application, with state and client side API queries. However, in the long term, we should eventually migrate this to server side rendering like the rest of our application. This is something I'd like the interns to work on and take their time with, in order for them to gain a better understanding of what SSR is and how it works.

**Comment by taesungh** [comment]
Admin site mostly imported, will get #118 done first since waiting on #163 before submitting PR for #189 after which I can submit a PR for this.
