### ISSUE TITLE
[Application Form] In-progress application submission fails if deadline passes

### ISSUE THREAD

**Issue by IanWearsHat** [HackAtUCI/irvinehacks-site-2024#216]
if somebody has the application page open while the deadline closes, the client-side submission will fail without any indication of why.

_Originally posted by @taesungh in https://github.com/HackAtUCI/irvinehacks-site-2024/pull/203#pullrequestreview-1820151560_

**Comment by taesungh** [comment]
I think the simplest approach would be checking if past deadline during `handleSubmit` and showing a message accordingly. It might be simple to just reload the page to show the `ApplicationsClosed` messaged, although the wording about "if you already applied" might be a little confusing. Perhaps we could show different content on that view depending on the user's status (i.e. if user is logged in but hasn't applied, omit the "log in to visit your applicant portal" message.
