### ISSUE TITLE
[API] Provide endpoint to initiate waiver signing

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#217]
In the portal, we plan on having the user click a button with a link to initiate filling out the DocuSign [PowerForm](https://www.docusign.com/products/electronic-signature/features/powerforms) waiver.

It is possible to pre-complete some of the fields on the PowerForm by providing query parameters for email and name. However, because we don't have the user's email or name (only UID) in the frontend, we can create an endpoint in our API to generate a link to the PowerForm with those fields prefilled.

**Comment by taesungh** [comment]
Working on API integration to provide URL, Portal interface will be added as part of #221.
