### ISSUE TITLE
Import FastAPI backend from the Hack at UCI 2023 site

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#22]
This issue is devoted to setting up the We can reuse the same [FastAPI backend ](https://github.com/HackAtUCI/HackUCI-Site/tree/main/src/api) from the Hack at UCI 2023 site in this year's site.

**Comment by taesungh** [comment]
Separating work into #67, #68, #69, #70, and #71.

**Comment by taesungh** [comment]
Besides the admin API endpoints and smaller fixes, #93 should be the last major chunk for user-facing endpoints.

**Comment by samderanova** [comment]
Finished importing with #93 and #173.
