### ISSUE TITLE
[Admin site] Write logic to release application decisions

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#220]
In the admin portal, we can create a button that will release most recent review statuses for applicants to view.

Dependent on
- [x] #241
- [x] #242

**Comment by taesungh** [comment]
Decisions were released this morning using a manual API call to make the POST request. For future uses, there should be a button to run this operation. Ideally there should also be a locking mechanism to prevent concurrent executions of the release endpoint.

Will revisit as we will soon need a new mechanism for releasing waitlisted folks.

**Comment by samderanova** [comment]
Closing as completed by #247 and #259
