### ISSUE TITLE
Create new volunteer and organizer roles limited to check-ins only

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#267]
To start off the construction of our check-in process, we'll have to create new `volunteer` and `organizer` roles to grant them access to only the check-in page on the admin site.

While there is a `tech_organizer` role currently in use, it is not being used, so this can simply be replaced by the `organizer` role. Additionally, the `volunteer` role already exists, so the only role that really needs to be created is the `organizer` one.

**Comment by taesungh** [comment]
We already have the `volunteer` role in the API but will need an `organizer` role. We can also create a new `ORGANIZER_ROLES`, similar to `ADMIN_ROLES` which includes what we need from #268.

On the Admin site side, we should repurpose `adminRole.ts` as `authorization.ts` for various Admin-related authorizations.
- Update `isAdminRole` to allow `organizer` and `volunteer`
- Use separate `isApplicationManager` function for the previous admin roles (`director` and `reviewer`).
- Create an empty page called Participants for #269 and show this in the AdminSidebar
- Hide the Applicants path and restrict the related pages to roles which satisfy `isApplicationManager`
  - Could just redirect to Admin dashboard if unauthorized cause layout itself will check general `isAdminRole`

**Comment by taesungh** [comment]
Update: volunteers will not be assigned check-in duty, so we'll need to remove them. Will include as part of #326.
