### ISSUE TITLE
[Portal] Show warning for `ATTENDING` applicants about un-RSVP

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#277]
When an `ATTENDING` user is about to un-RSVP, we should show them a warning that they will not be able to re-RSVP. This could just be some bold red text above the button.

Note that `CONFIRMED` users will not see this message and can freely toggle RSVP and un-RSVP before the deadline. Only `ATTENDING` users should see this. This will allow waitlisted applicants to toggle before their RSVP deadline on the 23rd while those who were initially accepted in the first wave will not be able to toggle.

**Comment by taesungh** [comment]
We will also need to update the logic on the `VerticalTimeline` to show the "Attendance Confirmed" message for both `confirmed` and `attending` as well as the `ApplicantPortal` to show `ConfirmAttendance` also for `attending` status.
