### ISSUE TITLE
Hotfix: Landing JPG vs PNG

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#36]
Downloading the landing section background as a JPG removes the transparent background of the bottom, meaning that now the bottom of the background image is white instead of transparent. We should switch back to a PNG and increase the animation delay time to account for the longer time it will take to load it.

<img width="351" alt="image" src="https://github.com/HackAtUCI/irvinehacks-site-2024/assets/28026520/052e7bf9-b058-4df5-834e-b613f505dbcb">

**Comment by taesungh** [comment]
Didn't we have the correct version in #5?

**Comment by samderanova** [comment]
Yes, but I replaced it with a JPG to resolve slow loading times on production, without realizing that they don't support transparent backgrounds. I actually missed it because my screen was just the right size so that the CSS ended up covering the white background at the bottom.

**Comment by taesungh** [comment]
There's no white background in the previous version from d2c1b32.

**Comment by samderanova** [comment]
That's a different image with no transparent background at all, which didn't provide a good transition into the background of the about section. This was the main reason why we switched to the transparent one.
