### ISSUE TITLE
Set up MongoDB connection

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#67]
As with [last year](https://github.com/HackAtUCI/HackUCI-Site/blob/main/src/api/services/mongodb_handler.py), we'll be using MongoDB to store application data and magic links for non-UCI applicants. We first need to create a new project on the MongoDB database (cc. @taesungh )  and then import the necessary functions from last year's backend into this repository.

**Comment by taesungh** [comment]
Note: we could consider including a Dockerfile to locally run a MongoDB instance and perhaps a Docker Compose configuration to provide the environment variable with the URI to the API runner.
See [mongo image on Docker Hub](https://hub.docker.com/_/mongo).

**Comment by taesungh** [comment]
Completed in #72.
