### ISSUE TITLE
Set up guest authentication

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#68]
As with last year, in order to allow applicants from other schools to log into their accounts, we should set up emails containing magic links will be sent to them.

This is another feature that can be imported from [last year's website](https://github.com/HackAtUCI/HackUCI-Site/blob/main/src/api/auth/guest_auth.py).

**Comment by taesungh** [comment]
Backend added in #92, pending frontend guest login page in #89.

**Comment by taesungh** [comment]
Added temporary functional login forms in #98, considering guest authentication API as complete.
