### ISSUE TITLE
Create login pages

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#81]
This page should exist on `/login`, consisting of a form that has only one input asking for the user's email.

~~The user must enter a `.edu` address. If the address is a `uci.edu` one, we should redirect them to `/api/saml/login`, which is where our UCI Shibboleth login is placed. Otherwise, we should send a POST request to `/api/guest/login` containing the body `{ email: [user's email] }` and redirect them to a guest login page telling them that a magic link has been emailed to them (see #68).~~

Edit: As [`LoginForm`](https://github.com/HackAtUCI/HackUCI-Site/blob/main/src/views/login/components/LoginForm.tsx) implies, if the email is valid, we can redirect to `/api/user/login`.

**Comment by samderanova** [comment]
In terms of design, see [last year's login page](https://hackuci.com/login) for an example. We'll want to add some margin to the sides on mobile though.

**Comment by taesungh** [comment]
For sake of unblocking #89, will be doing an unstyled import of the `ValidatingForm` from last year.
