### ISSUE TITLE
Guest Login Page

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#89]
Once non-UCI users enter their emails, they should be sent to a guest login page notifying them that they have been emailed a passphrase. See [`GuestLogin`](https://github.com/HackAtUCI/HackUCI-Site/blob/main/src/views/guest-login/GuestLogin.tsx) for details on how to implement this.

**Comment by taesungh** [comment]
Note: backend was added in #92. We'll want to revert 7bd7405 when adding the frontend guest verification page.

**Comment by rileysw** [comment]
Design is dependent on #86

**Comment by taesungh** [comment]
@alexanderl19, unstyled functional form added in #98, design with working custom validation was provided in #114 which can be copied.
