### ISSUE TITLE
Enable application submission to backend route

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#90]
Currently, submitting an application does not properly send it to the backend. The form's `action` should be set to `/api/user/apply`.

**Comment by taesungh** [comment]
As noted in #97, the native POST request will work for now, but it would be better to have client-side error handling in case anything goes wrong during the form submission (notably user session expires) in which case we would need to use `event.preventDefault` and then send the POST request ourselves with axios or alike.

**Comment by taesungh** [comment]
Thought we unlinked it from the PR but guess GitHub thought otherwise.
Additional note looking from last year's: the application form contains some write-in "Other" fields which we previously handled with the client-side submission. Since we are using SSR, it may be worth implementing this on the API side since someone could technically have JavaScript disabled. We can revisit this.

**Comment by samderanova** [comment]
To better handle situations in which a user's session has expired, we should write some additional code to send a request using [`axios`](https://axios-http.com/docs/intro) along with error handling to display a notification when the session expires. 

As a result, we also need to handle the situation where a user has JavaScript disabled. The `axios` request would not be sent, so we automatically fall back on native POST requests. If a user has JS disabled and submits without selecting any options labelled "Other", then we can safely continue to process this request. Otherwise, we should display some 400 status code (see #93) to tell the user to enable JS because the native POST request will send "Other" as the value for the specific question (i.e. major, pronouns, etc.) instead of the actual value the user provided.
