### ISSUE TITLE
Add API endpoint to accept hacker application

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#93]
The endpoint `/api/user/apply` needs to be set up in order to process applications properly. This should be a simple copy and paste from [last year's website](https://github.com/HackAtUCI/HackUCI-Site/blob/0b181fb750094373e2ab3f689d2691312bb88ee7/src/api/routers/user.py#L62).

**Comment by taesungh** [comment]
See PR discussion about lingering submission issues, also tracking in #90.

**Comment by samderanova** [comment]
As mentioned in #90, we need to add additional code in the backend to detect whether a user's application contains the value "Other" for one of the fields (meaning the user has disabled JS). If so, we should return some 400 status code.
